# Generated by Django 2.1.1 on 2018-10-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_babyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='babyprofile',
            name='image',
            field=models.ImageField(blank=True, default='profile_image/flower.png', upload_to='baby_profile_image'),
        ),
        migrations.AlterField(
            model_name='babyprofile',
            name='born_location',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
