# Generated by Django 2.1.1 on 2018-09-25 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180925_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='profile_image/flower.png', upload_to='profile_image'),
        ),
    ]
