# Generated by Django 2.1.1 on 2018-10-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='milestones'),
        ),
    ]
