# Generated by Django 2.1.1 on 2018-10-23 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_milestone_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='image',
        ),
    ]
