# Generated by Django 2.1.1 on 2018-09-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='image',
            field=models.ImageField(upload_to='calendar_image/%Y/%m/%d'),
        ),
    ]
