# Generated by Django 2.1.1 on 2018-09-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_auto_20180922_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='tags',
            field=models.ManyToManyField(to='album.Tag'),
        ),
    ]
