# Generated by Django 2.1.1 on 2018-09-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_auto_20180922_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='posts',
            field=models.ManyToManyField(to='album.Calendar'),
        ),
    ]
