# Generated by Django 2.1.1 on 2018-11-06 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_auto_20181106_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yunlist',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_content', to='album.YunList'),
        ),
    ]
