# Generated by Django 2.1.1 on 2018-11-06 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0005_auto_20181106_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yunlist',
            old_name='title',
            new_name='list',
        ),
        migrations.RemoveField(
            model_name='yunlist',
            name='content',
        ),
        migrations.RemoveField(
            model_name='yunlist',
            name='parent',
        ),
        migrations.AddField(
            model_name='yunlist',
            name='main_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_contents', to='album.YunList'),
        ),
        migrations.AddField(
            model_name='yunlist',
            name='sub_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_contents', to='album.YunList'),
        ),
    ]
