# Generated by Django 2.1.1 on 2018-09-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0005_auto_20180923_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='tags',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
