# Generated by Django 2.1.1 on 2018-11-07 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0006_auto_20181107_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yunlist',
            old_name='list',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='yunlist',
            name='main_content',
        ),
        migrations.RemoveField(
            model_name='yunlist',
            name='sub_content',
        ),
        migrations.AddField(
            model_name='yunlist',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='album.YunList'),
        ),
        migrations.AddField(
            model_name='yunlist',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='album.YunList'),
        ),
    ]
