# Generated by Django 2.1.1 on 2018-11-07 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0007_auto_20181107_0301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yunlist',
            old_name='post',
            new_name='content',
        ),
    ]
