# Generated by Django 2.1.1 on 2018-11-08 18:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('album', '0009_auto_20181108_1930'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostImage',
            new_name='Image',
        ),
    ]
