# Generated by Django 2.1.1 on 2018-10-10 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0009_notification_location_pk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='location_pk',
        ),
        migrations.AddField(
            model_name='notification',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='image_comments_notification', to='album.Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments_notification', to='album.Calendar'),
            preserve_default=False,
        ),
    ]
