# Generated by Django 2.1.1 on 2018-09-23 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0009_auto_20180923_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='tag',
            new_name='emoticon',
        ),
    ]
