# Generated by Django 2.1.1 on 2018-11-10 18:15

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0010_auto_20181108_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[1600, 1200], upload_to='calendar_image/%Y/%m'),
        ),
    ]
