# Generated by Django 2.1.1 on 2018-09-24 22:27

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0010_auto_20180924_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='calendar_image/%Y/%m'),
        ),
    ]
