# Generated by Django 2.1.1 on 2018-09-24 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0011_auto_20180925_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='thumbnail_height',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calendar',
            name='thumbnail_width',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calendar',
            name='image',
            field=models.ImageField(upload_to='calendar_image/%Y/%m'),
        ),
    ]
