# Generated by Django 2.1.1 on 2018-09-24 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0012_auto_20180925_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='thumbnail_height',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='thumbnail_width',
        ),
    ]
