# Generated by Django 2.1.1 on 2018-10-10 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0012_notification_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='comment',
        ),
    ]
