# Generated by Django 2.1.1 on 2018-09-26 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0014_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='image',
        ),
    ]
