# Generated by Django 2.1.1 on 2018-09-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0015_remove_calendar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=200),
        ),
    ]
