# Generated by Django 2.1.1 on 2018-10-10 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0015_auto_20181011_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='comment',
        ),
    ]
