# Generated by Django 2.1.1 on 2018-10-13 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0017_auto_20181011_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='image_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_comments_notification', to='album.ImageComment'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='post_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments_notification', to='album.Comment'),
        ),
    ]
