# Generated by Django 2.1.1 on 2018-09-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0017_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
