# Generated by Django 2.1.1 on 2018-09-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0019_imagecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
