# Generated by Django 2.1.1 on 2018-10-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0020_auto_20180930_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='emoticon',
            field=models.CharField(choices=[('HAPPY', 'happy'), ('SLEEPY', 'sleepy'), ('SICK', 'sick')], max_length=100),
        ),
    ]
