# Generated by Django 2.1.1 on 2018-10-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0021_auto_20181001_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='emoticon',
            field=models.CharField(max_length=100),
        ),
    ]
