# Generated by Django 2.1.1 on 2018-10-16 21:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('album', '0021_imagecomment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
