# Generated by Django 2.1.1 on 2018-10-17 00:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('album', '0022_calendar_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.ManyToManyField(related_name='image_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
