# Generated by Django 2.1.1 on 2018-10-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0022_auto_20181002_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='emoticon',
            field=models.CharField(choices=[('happy', 'happy'), ('sleepy', 'sleepy'), ('sick', 'sick')], max_length=100),
        ),
    ]
