# Generated by Django 2.1.1 on 2018-10-17 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0023_image_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
