# Generated by Django 2.1.1 on 2018-10-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0023_auto_20181002_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='emoticon',
            field=models.CharField(max_length=100),
        ),
    ]
