# Generated by Django 2.1.1 on 2018-10-17 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0024_notification_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='image_comment',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='post_comment',
        ),
        migrations.AddField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_notification', to='album.Calendar'),
        ),
    ]
