# Generated by Django 2.1.1 on 2018-10-01 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0024_auto_20181002_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='emoticon',
            field=models.CharField(choices=[('happy', 'Happy'), ('sleepy', 'Sleepy'), ('sick', 'Sick')], max_length=100),
        ),
    ]
