# Generated by Django 2.1.1 on 2018-10-02 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0025_auto_20181002_0152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emoticon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('happy', 'Happy'), ('sleepy', 'Sleepy'), ('sick', 'Sick')], max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='emoticon',
        ),
        migrations.AddField(
            model_name='calendar',
            name='emoticon',
            field=models.ManyToManyField(to='album.Emoticon'),
        ),
    ]
