# Generated by Django 2.1.1 on 2018-10-17 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0026_auto_20181017_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_notification', to='album.Image'),
        ),
    ]
