# Generated by Django 2.1.1 on 2018-10-02 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0026_auto_20181002_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='emoticon',
            name='image',
            field=models.ImageField(default=1, upload_to='emoticons/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emoticon',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
