# Generated by Django 2.1.1 on 2018-10-02 01:21

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0028_remove_emoticon_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='emoticon',
        ),
        migrations.AddField(
            model_name='calendar',
            name='emoticon',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('happy', 'Happy'), ('sleepy', 'Sleepy'), ('sick', 'Sick')], default=1, max_length=17),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Emoticon',
        ),
    ]
